<Project>
  <PropertyGroup>
    <Edition Condition="'$(Edition)' == ''">Simple</Edition>
    <BaseIntermediateOutputPath>obj\$(Edition)\</BaseIntermediateOutputPath>
    <BaseOutputPath>bin\$(Edition)\</BaseOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);**/obj/**;**/bin/**;artifacts/**</DefaultItemExcludes>
    <DefineConstants Condition="'$(Edition)' == 'Simple'">$(DefineConstants);SIMPLE_EDITION</DefineConstants>
  </PropertyGroup>
</Project>
