<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../RoutingPolicy.cs" Link="RoutingPolicy.cs" />
    <Compile Include="../RoutingConfiguration.cs" Link="RoutingConfiguration.cs" />
    <Compile Include="../InputProfile.cs" Link="InputProfile.cs" />
  </ItemGroup>
</Project>
